version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paint_management_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
    ports:
      - "3306:3306"
    networks:
      - springboot-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  springboot-app:
    build: .
    container_name: springboot-container
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - springboot-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/paint_management_db
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

networks:
  springboot-network:
    driver: bridge
